//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Purchase = new HashSet<Purchase>();
        }
    
        public int AId { get; set; }
        public Nullable<int> UId { get; set; }
        public string AAddressL1 { get; set; }
        public string AAddressL2 { get; set; }
        public string ACity { get; set; }
        public string ADistrict { get; set; }
        public string AState { get; set; }
        public string AEmail1 { get; set; }
        public string AEmail2 { get; set; }
        public string APhone1 { get; set; }
        public string APhone2 { get; set; }
        public string APIN { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchase { get; set; }
    }
}
