//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int BId { get; set; }
        public int UId { get; set; }
        public double RRating { get; set; }
        public string RComments { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}
