//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Address = new HashSet<Address>();
            this.Cart = new HashSet<Cart>();
            this.Purchase = new HashSet<Purchase>();
            this.Rating = new HashSet<Rating>();
        }
    
        public int UId { get; set; }

        [Required]
        [Display(Name = "Username")]
        public string UUserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string UPassword { get; set; }

        //[Required]
        //[Display(Name = "First Name")]
        public string UFName { get; set; }

        //[Required]
        //[Display(Name = "Last Name")]
        public string ULName { get; set; }

        //[Required]
        //[Display(Name = "Date of Birth")]
        public System.DateTime UDOB { get; set; }

        //[Required]
        //[Display(Name = "E-mail")]
        public string UEmail { get; set; }

        //[Required]
        //[Display(Name = "Phone")]
        public string UPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Rating { get; set; }
    }
}
